name: Upload to GCS
on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        version: latest
        project_id: test-app-edf74
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: src/index.js
        destination: github-action-test-tom