name: Upload to GCS
on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
    #   with:
    #     version: latest
    #     project_id: test-app-edf74
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true

    - name: Delet files from bucket
      run: gcloud storage rm gs://github-action-test-tom/**

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: 'build'
        destination: github-action-test-tom
        parent: false